import streamlit as st
import pandas as pd
from generator import get_or_create_template

st.set_page_config(page_title="AI Outreach Generator", layout="wide")

st.title("AI Outreach Assistant (Optimized for 1000s of Leads)")
st.write("Upload your lead CSV (name, city, tone). Messages are generated by city and tone, and personalized using {name} and {city} placeholders.")

uploaded_file = st.file_uploader("Upload CSV (name, city, tone)", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.success(f"Uploaded {len(df)} leads")

    output = []
    progress = st.progress(0)
    total = len(df)

    grouped = df.groupby(['city', 'tone'])

    for (city, tone), group in grouped:
        template = get_or_create_template(city, tone)

        for _, row in group.iterrows():
            name = row.get("name", "Friend")
            filled_message = template.replace("{name}", name).replace("{city}", city)
            output.append({
                "name": name,
                "city": city,
                "tone": tone,
                "message": filled_message
            })
            progress.progress(len(output) / total)

    result_df = pd.DataFrame(output)
    st.dataframe(result_df)

    csv = result_df.to_csv(index=False).encode('utf-8')
    st.download_button("Download Messages", data=csv, file_name="outreach_messages.csv", mime='text/csv')
